

services:
  backend:
    build: .
    container_name: vistaview_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/backend/data
      - ./app:/app/app
    environment:
      - MINIO_DISABLED=false
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio12345
      - MINIO_BUCKET=vistaview-catalog
      - MINIO_PUBLIC_BASE_URL=http://localhost:9000
      - MINIO_SECURE=false
      - PYTHONUNBUFFERED=1
    depends_on:
      - minio
      - postgres
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15
    container_name: vistaview_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vistaview
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: vistaview_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
